"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = '''
[](tertiary)$os[ ](bg:tertiary)$username$sudo[ ](bg:tertiary_fixed fg:tertiary)$directory[ ](bg:secondary fg:tertiary_fixed)$git_branch$git_commit$git_metrics$git_status$git_state[ ](bg:secondary_fixed fg:secondary)$kotlin$java$gradle$cpp$c$python$nodejs$lua$rust[ ](bg:primary fg:secondary_fixed)$time[](bg:primary_fixed fg:primary)$cmd_duration$character
'''
palette = 'yolk'
continuation_prompt = '[ ](fg:primary_fixed) '

[package]
disabled = true

[sudo]
disabled = false
style = 'fg:on_tertiary bg:tertiary'
symbol = '󱗒 '
format = '[ $symbol]($style)'

[username]
style_user = 'fg:on_tertiary bg:tertiary'
show_always = true
format = '[$user]($style)'

[os]
disabled = false
style = 'fg:on_tertiary bg:tertiary'
format = '[$symbol]($style)'

[os.symbols]
Fedora = ''

[directory]
style = 'fg:on_tertiary_fixed bg:tertiary_fixed'
format = '[$path ]($style)'
use_os_path_sep = false
truncation_length = 1
fish_style_pwd_dir_length = 1

[directory.substitutions]#brakes fish style pwd dir
#'io/github/pinguinlars' = ''

[git_branch]
format = '[$symbol $branch ]($style)'
style = 'bg:secondary fg:on_secondary'
symbol = '󰘬'
#ignore_branches = ['master', 'main']

[git_commit]
format = '[ $hash$tag]($style)'
tag_symbol = ''
style = 'bg:secondary fg:on_secondary'

[git_state]#TODO

[git_metrics]
disabled = false
added_style = 'bg:secondary fg:on_secondary'
deleted_style = 'bg:secondary fg:on_secondary'
format = '[+$added ]($added_style)[-$deleted ]($deleted_style)'
only_nonzero_diffs = true

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
style = 'bg:secondary fg:on_secondary'
use_git_executable = true

[kotlin]
symbol = '󱈙'
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${major}.${minor}'
format = '[$symbol $version ]($style)'

[java]
symbol = '󰛊'
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${major}'
format = '[$symbol $version ]($style)'

[gradle]
symbol = ''
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${raw}'
format = '[$symbol $version ]($style)'

[python]
symbol = '󰌠'
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${major}.${minor}'
format = '[$symbol $version ]($style)'

[cpp]
symbol = ''
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${major}.${minor}'
format = '[$symbol $name $version ]($style)'

[c]
symbol = ''
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${major}.${minor}'
format = '[$symbol $name-$version ]($style)'

[nodejs]
symbol = ''
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${major}'
format = '[$symbol $version ]($style)'

[lua]
symbol = '󰢱'
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${major}.${minor}'
format = '[$symbol $version ]($style)'

[rust]
symbol = '󱘗'
style = 'bg:secondary_fixed fg:on_secondary_fixed'
version_format = 'v${major}.${minor}'
format = '[$symbol $version ]($style)'

[time]
disabled = false
style = 'bg:primary fg:on_primary'
format = '[󰥔 $time ]($style)'
time_format = '%H:%M'

[character]
format = '$symbol '
success_symbol = '[](fg:primary_fixed bg:primary_fixed)[](fg:primary_fixed)'
error_symbol = '[](fg:primary_fixed bg:error)[](fg:error)'
vimcmd_symbol = '[](fg:primary_fixed bg:primary_fixed)[](fg:primary_fixed)'

[cmd_duration]
style = 'bg:primary_fixed fg:on_primary_fixed'
format = '[ 󱦟 $duration]($style)'

[palettes.rosepine]

#gets synced with yolk
[palettes.yolk]
#{#rcol(data.colors.background)#}
background = "#131318"
#{#rcol(data.colors.error)#}
error = "#ffb4ab"
#{#rcol(data.colors.error_container)#}
error_container = "#93000a"
#{#rcol(data.colors.inverse_on_surface)#}
inverse_on_surface = "#303036"
#{#rcol(data.colors.inverse_primary)#}
inverse_primary = "#525a92"
#{#rcol(data.colors.inverse_surface)#}
inverse_surface = "#e4e1e9"
#{#rcol(data.colors.on_background)#}
on_background = "#e4e1e9"
#{#rcol(data.colors.on_error)#}
on_error = "#690005"
#{#rcol(data.colors.on_error_container)#}
on_error_container = "#ffdad6"
#{#rcol(data.colors.on_primary)#}
on_primary = "#232c61"
#{#rcol(data.colors.on_primary_container)#}
on_primary_container = "#dee0ff"
#{#rcol(data.colors.on_primary_fixed)#}
on_primary_fixed = "#0b154b"
#{#rcol(data.colors.on_primary_fixed_variant)#}
on_primary_fixed_variant = "#3a4379"
#{#rcol(data.colors.on_secondary)#}
on_secondary = "#2d2f42"
#{#rcol(data.colors.on_secondary_container)#}
on_secondary_container = "#e0e1f9"
#{#rcol(data.colors.on_secondary_fixed)#}
on_secondary_fixed = "#181a2c"
#{#rcol(data.colors.on_secondary_fixed_variant)#}
on_secondary_fixed_variant = "#434559"
#{#rcol(data.colors.on_surface)#}
on_surface = "#e4e1e9"
#{#rcol(data.colors.on_surface_variant)#}
on_surface_variant = "#c7c5d0"
#{#rcol(data.colors.on_tertiary)#}
on_tertiary = "#44263d"
#{#rcol(data.colors.on_tertiary_container)#}
on_tertiary_container = "#ffd7f1"
#{#rcol(data.colors.on_tertiary_fixed)#}
on_tertiary_fixed = "#2d1227"
#{#rcol(data.colors.on_tertiary_fixed_variant)#}
on_tertiary_fixed_variant = "#5d3c54"
#{#rcol(data.colors.outline)#}
outline = "#90909a"
#{#rcol(data.colors.outline_variant)#}
outline_variant = "#46464f"
#{#rcol(data.colors.primary)#}
primary = "#bbc3ff"
#{#rcol(data.colors.primary_container)#}
primary_container = "#3a4379"
#{#rcol(data.colors.primary_fixed)#}
primary_fixed = "#dee0ff"
#{#rcol(data.colors.primary_fixed_dim)#}
primary_fixed_dim = "#bbc3ff"
#{#rcol(data.colors.scrim)#}
scrim = "#000000"
#{#rcol(data.colors.secondary)#}
secondary = "#c4c5dd"
#{#rcol(data.colors.secondary_container)#}
secondary_container = "#434559"
#{#rcol(data.colors.secondary_fixed)#}
secondary_fixed = "#e0e1f9"
#{#rcol(data.colors.secondary_fixed_dim)#}
secondary_fixed_dim = "#c4c5dd"
#{#rcol(data.colors.shadow)#}
shadow = "#000000"
#{#rcol(data.colors.surface)#}
surface = "#131318"
#{#rcol(data.colors.surface_bright)#}
surface_bright = "#39393f"
#{#rcol(data.colors.surface_container)#}
surface_container = "#1f1f25"
#{#rcol(data.colors.surface_container_high)#}
surface_container_high = "#29292f"
#{#rcol(data.colors.surface_container_highest)#}
surface_container_highest = "#34343a"
#{#rcol(data.colors.surface_container_low)#}
surface_container_low = "#1b1b21"
#{#rcol(data.colors.surface_container_lowest)#}
surface_container_lowest = "#0d0e13"
#{#rcol(data.colors.surface_dim)#}
surface_dim = "#131318"
#{#rcol(data.colors.surface_tint)#}
surface_tint = "#bbc3ff"
#{#rcol(data.colors.surface_variant)#}
surface_variant = "#46464f"
#{#rcol(data.colors.tertiary)#}
tertiary = "#e6bad7"
#{#rcol(data.colors.tertiary_container)#}
tertiary_container = "#5d3c54"
#{#rcol(data.colors.tertiary_fixed)#}
tertiary_fixed = "#ffd7f1"
#{#rcol(data.colors.tertiary_fixed_dim)#}
tertiary_fixed_dim = "#e6bad7"
