"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](default_bg)$username$hostname[](default_bg) \
$directory\
$status\
$fill\
$c\
$cpp\
$cmake\
$gleam\
$go\
$gradle\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$python\
$rust
$character"""
right_format = "$time"

palette = "uwu"

[palettes.uwu]
time_bg = "#334b4f" # {<rcol(data.colors.starship_time_bg)>}
time = "#cde7ec" # {<rcol(data.colors.starship_time)>}
default_bg = "#004f58" # {<rcol(data.colors.starship_default_bg)>}
default = "#9eeffd" # {<rcol(data.colors.starship_default)>}
succes = "#82d3e1" #{<rcol(data.colors.normal)>}
error = "#ffb4ab" #{<rcol(data.colors.critical)>}

[directory]
format = "[](default_bg)[$read_only$path]($style)[](default_bg) "
style = "bg:default_bg fg:default"
read_only = '󰉐 '
fish_style_pwd_dir_length = 1
truncation_length = 1
use_os_path_sep = false # / everywhere
use_logical_path = true # resolve symlinks

[character]
success_symbol = "[󱞪](succes)"
error_symbol = "[󱞪](error)"

[time]
disabled = false
time_format = "%R"
format = "[](time_bg)[󰅐 $time](bg:time_bg fg:time)"

[username]
show_always = true
style_user = "fg:default bg:default_bg"
style_root = "fg:error bg:default_bg"
format = "[󰧱 $user]($style)"
aliases = { lars = "ashley" } # {< if !school_mode>}

[hostname]
style = "fg:default bg:default_bg"
format = "[@$hostname]($style)"

[status]
disabled = false
map_symbol = true
pipestatus = true
success_style = "fg:default bg:default_bg"
failure_style = "fg:error bg:default_bg"
symbol = ' '
not_executable_symbol = ''
not_found_symbol = '󰍉 '
sigint_symbol = ' '
signal_symbol = '󰞏 '
format = "[](default_bg)[$symbol$status]($style)[](default_bg)"
pipestatus_separator = "[|](default_bg)"
pipestatus_format = "$pipestatus [=>](default) [](default_bg)[$symbol$status]($style)[](default_bg)"

[fill]
symbol = ' '


#: langs

#: template

# [lang]
# format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
# version_format = 'v${raw}'
# symbol = ''
# style = 'fg:default bg:default_bg'

[c]
format = ' [](default_bg)[$symbol$version|$name]($style)[](default_bg)'
version_format = 'v${major}.${minor}'
symbol = ' '
style = "fg:default bg:default_bg"
commands = [ [ 'clang', '--version' ], [ 'cc', '--version' ], [ 'gcc', '--version' ] ]

[cpp]
format = ' [](default_bg)[$symbol$version|$name]($style)[](default_bg)'
version_format = 'v${major}.${minor}'
symbol = ' '
style = 'fg:default bg:default_bg'
disabled = false
commands = [ ['clang++','--version'], [ 'c++', '--version' ], [ 'g++', '--version' ] ]

[cmake]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${raw}'
symbol = ' '
style = 'fg:default bg:default_bg'

[gleam]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${major}.${minor}'
symbol = ' '
style = 'fg:default bg:default_bg'

# [go] #bugged
# format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
# version_format = 'v${raw}'
# symbol = '󰟓 '
# style = 'fg:default bg:default_bg'

[gradle]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${raw}'
symbol = ' '
style = 'fg:default bg:default_bg'

[java]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${major}'
symbol = '󰅶 '
style = 'fg:default bg:default_bg'

[julia]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${raw}'
symbol = ' '
style = 'fg:default bg:default_bg'

[kotlin]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${major}.${minor}'
symbol = ' '
style = 'fg:default bg:default_bg'

[lua]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${raw}'
symbol = '󰢱 '
style = 'fg:default bg:default_bg'

[nodejs]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${major}.${minor}'
symbol = ' '
style = 'fg:default bg:default_bg'

[python]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${major}.${minor}'
symbol = ' '
style = 'fg:default bg:default_bg'

[rust]
format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
version_format = 'v${major}.${minor}'
symbol = ' '
style = 'fg:default bg:default_bg'

#: template

# [lang]
# format = ' [](default_bg)[$symbol$version]($style)[](default_bg)'
# version_format = 'v${raw}'
# symbol = ''
# style = 'fg:default bg:default_bg'

